language: cpp

arch:
  - arm64
  - amd64
dist: bionic 

compiler:
  - gcc
before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential pkg-config automake libtool git zlib1g-dev
  - sudo apt-get install -y libboost-dev libboost-system-dev libboost-chrono-dev libboost-random-dev libssl-dev libgeoip-dev
install: 
  - git clone https://github.com/arvidn/libtorrent.git
script:
  - cd libtorrent
  - ./autotool.sh
  - ./configure --disable-debug --enable-encryption CXXFLAGS="-std=c++14"
  - make clean && make -j$(nproc)
  - sudo make install
  - make install DESTDIR=$PWD/_intsall
  - tar xvf libtorrent.tar ./_install
  - sudo apt-get install -y qtbase5-dev qttools5-dev-tools libqt5svg5-dev
  - cd ..
  - mkdir  deploy
  - mv libtorrent/libtorrent.tar deploy/.
  - git clone https://github.com/qbittorrent/qBittorrent
  - cd qBittorrent
  - latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
  - echo checking out ${latestTag}
  - git checkout ${latestTag}
  - ./configure --disable-gui CXXFLAGS="-std=c++14"
  - make clean && make -j$(nproc)
#  - make install DESTDIR=$PWD/_install
  - ./src/qbittorrent-nox -v
  - tar cvf qbittorrent-nox.tar ./src/qbittorrent-nox
  - mv qbittorrent-nox.tar ../deploy/.
  - cd ..
 deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: deploy/*
  skip_cleanup: true
  on:
    tags: true
