on:
  watch:
    types: [started]
jobs:
  libtorrent:
    runs-on: ubuntu-18.04
    name: Build on aarch64 
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: uraimo/run-on-arch-action@v1.0.5
        id: runcmd
        with:
          architecture: aarch64
          distribution: ubuntu18.04
          run: |
            apt-get update
            apt-get install -y build-essential pkg-config automake libtool git zlib1g-dev
            apt-get install -y libboost-dev libboost-system-dev libboost-chrono-dev libboost-random-dev libssl-dev libgeoip-dev
            git clone https://github.com/arvidn/libtorrent.git
            cd libtorrent
            ./autotool.sh
            ./configure --disable-debug --enable-encryption CXXFLAGS="-std=c++14"
             make clean && make -j$(nproc)
             make install
